### PR TITLE
stm32/f0 clock updates: HSI cleanup and HSE support

### PR DESCRIPTION
**Pull request by geomatsi**
Hi all,
This PR includes patches doing the following things:
- add more clock helper functions
- minor cleanup of HSI setup functions: use new helpers rather than directly manipulate registers
- add brief doxigen descriptions for HSI setup functions
- implement HSE setup functions

Tested on a custom board based on stm32f030f4p6 chip.

Regards,
Sergey

### CODE REVIEW

**Comment by allesblinkt** [comment]
Thank you very much. Those additions have been very helpful. Using these additions to configure the clock from an external crystal works very nicely.

**Comment by geomatsi** [comment]
v1 -> v2:
- fix commit message
- rebase on top of latest changes

**Comment by geomatsi** [comment]
v2 -> v3: no changes, rebase on top of master and make sure that everything is ok

**Comment by karlp** [comment]
These look good. I'm going to merge them all, but I'm dropping 
```
void rcc_clock_setup_in_hse_8mhz_out_8mhz(void);
void rcc_clock_setup_in_hse_8mhz_out_16mhz(void);
void rcc_clock_setup_in_hse_8mhz_out_32mhz(void);
```

I don't see a lot of need in the helpers for various intermediate speeds.  Eventually, f0 will move as everything else except f1, and have struct based rcc init, but I'll have this one in for now.

**Comment by karlp** [comment]
this has now landed in 1b97ece..0259102 thanks!

**Pull request closed without merging**
