### PR TITLE
README: added info about partial build

### PR DESCRIPTION
**Pull request by a-v-v**
This commit resolves issue #1263.

### CODE REVIEW

**Comment by a-v-v** [comment]
I can close this pull request, if it is unecessary.

**Comment by karlp** [comment]
no, it fixes an issue, there's no reason to close it.

**Comment by schodet** [comment]
There seems to be no way to push additional commits to someone else PR, I made some suggestion here:

https://github.com/schodet/libopencm3/tree/readme_build

- split white space change in another commit,
- remove list of targets from README to avoid duplicated work and add a list-targets in Makefile,
- replace “footprint of the library” by “build time”, as someone could wrongly understand that the compiled size of the lib depends on the list of built targets.

**Comment by karlp** [comment]
resolved via ed2aada3..8f016208 thanks!

**Pull request closed without merging**
