### PR TITLE
stm32f3: fix missing reg mask for adc_set_multi_mode

### PR DESCRIPTION
**Pull request by FrancoisFinfe**
Missing defines for ADC_CCR DUAL values have also been added.

### CODE REVIEW

**Comment by FrancoisFinfe** [comment]
My understanding is that stm32f3 only supports dual mode (ADC1 & 2) or (ADC3 & 4) and not triple mode.
Therefore, adc_set_multi_mode function could also be rename to adc_set_dual_mode (in this same commit).

**Comment by karlp** [comment]
I'd rather keep MULTI so that the same code can be used, but in general this patch is on the right track, definite bug in the implementation to not clear bits first.  We also prefer having unshifted forms of the bit definitions

**Comment by FrancoisFinfe** [comment]
Bit definitions hase been changed to unshifted.

**Comment by karlp** [comment]
Merged thanks! (Made some followup amendments)  _lots_ of this is common with l4, so I've filed that for anyone to work on  https://github.com/libopencm3/libopencm3/issues/1181

**Pull request merged**
