### PR TITLE
Cleanup and added the dma to the f7 series

### PR DESCRIPTION
**Pull request by RabbeS**
Hi,

I added the dma.h to the f7 series and did a little cleanup in the code.
**Please check** if its still working with the f2 or **f4**.

Best regards,
Stephan

### CODE REVIEW

**Comment by karlp** [comment]
So, you can see from the travis reports that it _doesn't_ work yet, or even compile.  Please try and fix those sorts of things before you ask other people to look at them where possible.

**Comment by RabbeS** [comment]
Sorry @karlp,

I wrote the code in my own project and just copied it into the pull request. During that process I forgot one part. Sorry that I wasted time :,(
Now it's compiling, so can you please check if its still working with the f2 or f4?

Thanks,
Stephan

**Comment by karlp** [comment]
Are you missing makefile changes for f2/f4?  Also, I'm not really sure about the name _all_ it most certainly doesn't apply to f1.  Honestly, leaving the filename at f24 is probably fine, and would make the actual _code changes_ much easier to see.  (currently, it's delete a whole file, and add whole new file that's got some changes, but I can't see what they are)

**Comment by RabbeS** [comment]
Ah okay so I'll rename only the file dma_common_f24 to dma_common_f247 to add the f7 series :)

**Pull request closed without merging**
