### PR TITLE
Remove unused Python variables

### PR DESCRIPTION
**Pull request by mnaberez**
Remove variables that are assigned by never used.

### CODE REVIEW

**Comment by karlp** [comment]
sure. ok, I guess.  Any reason you couldn't have put this in the last one? Are you planning on submitting more of these sorts of trivial things?  it's all good and clean and correct, but it's a timesuck.

**Comment by mnaberez** [comment]
> sure. ok, I guess. Any reason you couldn't have put this in the last one? 

I generally try to limit pull requests to one type of change so they're easier to review.  I review a lot of PRs myself and I don't enjoy PRs that fix or change several unrelated things.

> Are you planning on submitting more of these sorts of trivial things? it's all good and clean and correct, but it's a timesuck.

I am working on a large codebase that includes a significant Python portion and also has libopencm3.  We run the `pyflakes` static analyzer on it because it helps us find bugs.  It's nice to not have warnings from libopencm3 mixed in `pyflakes` output.

> If you are, could you please maybe batch them up a bit so I can look at them all in one go?

There are no more `pyflakes` warnings from libopencm3.

**Comment by karlp** [comment]
pulled into my staging too.

**Comment by karlp** [comment]
staging has landed.

**Pull request closed without merging**
