### PR TITLE
F4 rcc

### PR DESCRIPTION
**Pull request by jhalmen**
I'm working on a project with the f401. i've come across a few things i thought worth changing / adding.

short explanation for the current commits:
* the removed functionality can be accessed through `rcc_osc_on(RCC_PLLSAI);` respectively `rcc_is_osc_ready(RCC_PLLSAI);`
* add short wrapper to configure the i2s pll available on the stm32f401

### CODE REVIEW

**Comment by karlp** [comment]
Looks perfectly reasonable to me.  Are those removed functions also present on f7 or anywhere where we could drop them too?

**Comment by jhalmen** [comment]
i just checked, and i can't seem to find any.
but then again, f4 is the only family where i could find *any* pllsai functions

**Comment by OpenUAS** [comment]
Any reason not to merge?

**Comment by karlp** [comment]
This has now merged.  I changed the commit titles to match style, I changed the commit comments to include the replacement functions, I changed the documentation on range of values, as f405 et al also have this register, with different range of values.

**Pull request closed without merging**
