### PR TITLE
partially fixed #454 adc power off

### LINKED ISSUE #454: stm32f0/f3 ADC poweroff
According to the reference manual (DocID018940 Rev 7, page 233) following procedure should be used to disable an ADC.

*Set ADDIS=1 to disable the ADC and put the ADC in power down mode. The ADEN
and ADDIS bits are then automatically cleared by hardware as soon as the ADC is fully
disabled.*

But libopencm3 instead tries to clear the ADEN bit, which is not possible according to the manual (the bit has `rs` access).

This should be the correct way:
```C
    ADC_CR(ADC) |= ADC_CR_ADDIS;
    while (ADC_CR(ADC) & ADC_CR_ADEN);
```
In order to re-calibrate an ADC it is essential to make sure the ADC is fully powered off i.e. `ADEN=0`, so there should be a call like `adc_power_off_wait_finish(...)` since `adc_power_off(...)` is async.

Relevant implementation:
https://github.com/libopencm3/libopencm3/blob/master/lib/stm32/f0/adc.c

### PR DESCRIPTION
**Pull request by trichner**
This is the correct way to disable the ADC according to the reference manual. Note that this is asynchronous, the ADC will not stop immediatly, you need to check the ADEN flag to ensure its actually down.
Smoke-tested.

### CODE REVIEW

**Comment by karlp** [comment]
Can you please fix this for F3 as well?

**Comment by trichner** [comment]
I have no stm32f3 hardware around, so cannot test.

**Comment by karlp** [comment]
it doesn't need to be tested on the hardware, it's a pretty clear bug from the manual, with a clear simple fix.

**Comment by trichner** [comment]
just letting you know its untested :)

**Comment by karlp** [comment]
11:51 < n1b> I suspect there are some more issues there, I had problems setting ADDIS and then waiting for ADEN 
             to go to low.
11:51 < n1b> seemed to hang

**Comment by trichner** [comment]
I suggest you merge it as it is the correct implementation (according to the reference manual for STM32F0). The issues I had might as well be in other parts in my project.

**Comment by trichner** [comment]
any status update?

**Comment by trichner** [comment]
What stops this from merging?

**Comment by karlp** [comment]
round tuits mostly.  It certainly wasn't helpful that you said, "even with this, it doesn't work" and didn't follow up on it.  I haven't found the time to follow up on it myself either, so it's in the queue of "looks good, but seemed like it needed some verifying"   Also, adding in the rename (which is a good idea) means someone (me) wants to review the documentation and the common sections, make sure they're all documented as doing the same thing, make sure there's no slight differences in the different families, and that all families end up getting the same thing.  It's never quite as simple as "I'll just fix this for the one chip I'm working on"  The current string of commits don't have great titles or text, but generally just a lack of maintainer time.  I'm currently ignoring all but the most basic fixes that happen to land fully formed and easy to verify until I wrap up the USB infrastructure testing and merging.   It will happen, and when I have free time I do normally start with the oldest pulls and go through them methodically.

**Comment by trichner** [comment]
Thanks for the quick response, if I find the time I'll do some testing on STM32F0 and report back.

**Comment by karlp** [comment]
this has now landed (equivalents) via a large tree of adc cleanups for f0/f3/l4

**Pull request closed without merging**
