### PR TITLE
Add 100MHz clock config

### PR DESCRIPTION
**Pull request by sker65**
Added config, see issue https://github.com/libopencm3/libopencm3/issues/1302

### CODE REVIEW

**Comment by karlp** [comment]
Commit message needs to have all the information in it, why is this config relevant, for instance.  it can't just be "add 100meg" like it is now.  given that the f411 familiy does introduce a new top speed, I'm ok with adding it, but do it right :)

**Comment by sker65** [comment]
Did not find a CONTRIBUTE.md or something that describe that type of requirements on commit comments. What now? Could you not just add an additional comment line when merging it?

**Comment by karlp** [comment]
commit comments should _always_ say why, not what.  the what is in the code commit, the comment is to explain the why.  It also must stand alone, not rely on an external source like "fixes github 123" being available.

no, I will not do work for you.  My time is limited, and I absolutely do not scale to "fixing" commits for everyone who wants to contribute.

**Comment by sker65** [comment]
Oh man, my time is limited as well. The why is obvious: there are a couple of boards out their, that support the new timing configuration. I've created the structure and PR . Take it or leave it.

**Comment by ALTracer** [comment]
Please never ever consider merging this.
I'll add my 2 cents since I bought a couple of these boards.

1. It's impossible to clock both SYSCLK/HCLK at 100MHz and USB at 48MHz simultaneously, the Main PLL dividers pllp & pllq are not flexible enough. Best you can do is 96MHz, which is 4% off (remember the 24MHz Flash in these parts) and already supported.

2. This commit adds the struct into `rcc_hse_8mhz_3v3` array, but the WeAct MiniF4 boards have a 25MHz HSE. Also the dividers are calculated for 25MHz HSE (25/12*96/2=100). And it breaks indexing for all the other `rcc_hs*` arrays.

**Pull request closed without merging**
