### PR TITLE
STM32 ADC standardization and cleanup

### PR DESCRIPTION
**Pull request by karlp**
~~DEPENDS ON https://github.com/libopencm3/libopencm3/pull/561~~ merged

This is further work cleaning up some of the common functionality across the ADCs, paving the way for upcoming patches that reduce duplication and bring in L0 and L4 support, and merge the f0/f3 adc code.

### CODE REVIEW

**Comment by karlp** [comment]
@esden This one is "ready to go" I was just leaving it in my local tree while I worked on the rest of the "v2 adc" peripheral stuff for f0/f3/l0/l4 but it's just stalled out in my christmas overload.  All these parts are good to go though.  (#548 had some debate so I held it off for a bit longer, and it's in the adv c2 drafts branch instead of here)

**Comment by ChuckM** [comment]
:+1: looks good to me

**Comment by karlp** [comment]
(Also, it was waiting in the hopes someone else would see what I was doing and yea/nei it ;)

**Comment by karlp** [comment]
merged now, or equivalents at least.

**Pull request closed without merging**
