### PR TITLE
Add inital RCC subsystem support for the STM32F7.

### PR DESCRIPTION
**Pull request by Sync-**
Just uses the default reset clock. Actual PLL values coming later.

### CODE REVIEW

**Comment by karlp** [comment]
@Sync- this branch has gotten a  bunch of ethernet commits in it to that are out of scope for this pull, can you leave a different branch with just the f7 rcc pull bits please?

**Comment by Sync-** [comment]
Did so.

**Comment by karlp** [comment]
I want to merge this, and will do so, but do people have any opinions on which API they prefer?

1. uint32_t rcc_system_clock_source(void) and void rcc_set_sysclk_source(uint32_t clk)  (uses bit definitions) (used on f1, f3,f4,l4 and here, f7)
2. enum rcc_osc rcc_system_clock_source(void) and void rcc_set_sysclk_source(enum rcc_osc osc) (uses enums, used on f0, l0)

I kinda feel that API 2 is "nicer" for the user, though it's "fatter" library code.  Without comments, I guess I should just file this as an API issue?

**Comment by karlp** [comment]
I've pulled this in after modifying all the namespace prefixes as was done for other families after this PR was submitted.  There's definitely room for some future extraction of   common api code for RCC stuff, but   now's not the time for that.  Same for the blocking/non-blocking. It's just not the time for that in this commit.

**Comment by karlp** [comment]
I've pulled in (most?all?) of this in 3fc0c9d..d2540e5

**Pull request closed without merging**
