### PR TITLE
stm32f4: provide correct AHB frequency

### PR DESCRIPTION
**Pull request by smallzzy**

### CODE REVIEW

**Comment by karlp** [comment]
I see these are missing for f3, f4, l1.  Any chance you could expand this to cover those? clearly missing from the earlier commits in 9ddfcb0  and 40d9ffc

**Comment by smallzzy** [comment]
I have made additional comments. I never used these chips so I suppose they share the same properties.

**Comment by karlp** [comment]
:+1:

**Comment by karlp** [comment]
merged via rebase, thanks

**Pull request closed without merging**
