### PR TITLE
stm32l1: rcc: reliably clock up/down

### PR DESCRIPTION
**Pull request by karlp**
When changing the system clock, you must take care to not exceed the
legal ranges based on voltage and flash wait states.

Existing code made it possible to provide a valid clock structure, that
would run out of bounds temporarily.  Some boards would crash with
various Usage faults / Bus errors due to this.

https://github.com/karlp/libopencm3-tests/tree/master/tests/rcc-legal-ranges provides a test case that fails on most stm32l boards without this change.

Ideally, this needs to be extended to cover the PLL clocks, and then further out to other families.  For L1 at least, MSI is valid for all speeds in all ranges, only wait states might be questionable.

### CODE REVIEW

**Comment by ChuckM** [comment]
This looks like the right fix to me. I've tried it on the 469, 429, and 411 processors.

**Comment by karlp** [comment]
did you port that change locally? it's not code used on any f4 parts, so it shouldn't have changed anything there anway?

**Comment by ChuckM** [comment]
On the F4's is the flash wait states that screws them up. (not as problem going down through, but speeding up it hangs). Although on the 446 (which I didn't try) also has a wider voltage scaling range.

**Comment by karlp** [comment]
Still need to apply more of this to other clock setups, but more improvements more time

**Pull request merged**
