### PR TITLE
USART Idle interrupt enable/disable functions

### PR DESCRIPTION
**Pull request by seymar**
I added functions to enable/disable the USART Idle interrupt.

### CODE REVIEW

**Comment by smooker** [comment]
https://gist.github.com/smooker/b2ecc938b4c231f5eb0fff31e8c88648

**Comment by seymar** [comment]
@smooker Could you elaborate on the removal of the disable function? The other interrupts also have it.

**Comment by karlp** [comment]
@seymar  don't worry abotu that gist, I'm certainly not treating it as relevant, I'm not even sure they meant for it to be a comment here.

**Comment by karlp** [comment]
if you want to be awesome, look at other commits for what the comit subject line should look liek, and rebase this to a single commit.  You (almost definitely) want to to use a real branch for this, not just your own local master branch....

Otehrwise, I'll squish and reword eventually, it just takes longer.

**Comment by seymar** [comment]
Ah great, will do!

**Comment by karlp** [comment]
merged in f9d5fb73 thanks

**Pull request merged**
