### PR TITLE
Mention GNU awk requirement

### PR DESCRIPTION
**Pull request by spbnick**
Mention GNU awk (gawk) as being required, as the build would fail
with e.g. mawk.

E.g. libopencm3-examples fails with mawk like this:

      GENLNK  samd10d14
    arm-none-eabi-gcc -E -mcpu=cortex-m0plus -mthumb -msoft-float -DSAMD  -P -E /home/nick/projects/github.com/libopencm3/libopencm3-examples/libopencm3/ld/linker.ld.S > generated.samd10d14.ld
    arm-none-eabi-gcc --static -nostartfiles -Tgenerated.samd10d14.ld -mcpu=cortex-m0plus -mthumb -msoft-float -Wl,-Map=miniblink.map -Wl,--gc-sections -L/home/nick/projects/github.com/libopencm3/libopencm3-examples/libopencm3/lib miniblink.o -lopencm3_samd -Wl,--start-group -lc -lgcc -lnosys -Wl,--end-group -o miniblink.elf
    /usr/lib/gcc/arm-none-eabi/5.4.1/../../../arm-none-eabi/bin/ld:generated.samd10d14.ld:16: warning: memory region `rom' not declared
    /usr/lib/gcc/arm-none-eabi/5.4.1/../../../arm-none-eabi/bin/ld: invalid origin for memory region ram

### CODE REVIEW

**Comment by karlp** [comment]
I believe there's a ticket or a pull to remove the gawk requirement, which I find far more appealing :)

**Comment by spbnick** [comment]
@karlp Ah, that would be better, without doubt. Although, if that's going to take a while, merging this one would perhaps save some time for new users like me, in the meantime.

**Comment by karlp** [comment]
no-one reads them anyway, but sure, that can be done I guess :)

**Comment by karlp** [comment]
wrote somethign similar and pushed in 6b5edeb091caa97568aeaabd6e9e3a6de7d0f9da

**Pull request closed without merging**
