### PR TITLE
Adds ability to enable .eh_frame while generating linker script

### PR DESCRIPTION
**Pull request by denizzzka**
Usage: just pass ARCH_FLAGS=-D_EH_FRAME while run mk/*.mk files

### CODE REVIEW

**Comment by denizzzka** [comment]
I removed comment because it looks like copy and pasted, and eh_frame used not only with C++ and not only for exception handling

**Comment by karlp** [comment]
Care to elaborate on what it _is_ used for then?

**Comment by denizzzka** [comment]
For stack tracing and changing stackframes, as I know.
In any case there is no such comments on other variables in this file.

**Comment by denizzzka** [comment]
An idea came up: it is possible to add all comments from `cortex-m-generic.ld` into `linker.ld.S` and enable `-C` option "Do not discard comments" for gcc preprocessor. Then a more pleasant file will be generated.

**Comment by denizzzka** [comment]
This PR isn't usable, section leaved as not defined. External patching by build scripts will be better.

**Comment by karlp** [comment]
unifying the cortex-m-generic and the template for the generator is definitely a good idea, totally agree.  As for this PR,  ok? great :) that was easy :)

**Pull request closed without merging**
