### PR TITLE
stm32h7: added new bit defs for stm32h7 fmc async configuration.

### PR DESCRIPTION
**Pull request by vielster**

### CODE REVIEW

**Comment by vielster** [comment]
FYI, Section 21.7.6 of RM0433

image

**Comment by karlp** [comment]
If it's ok with you, I'll replace assync with async and turn some comments into /** style, but otherwise this looks fine.

**Comment by vielster** [comment]
Haha...I guess my mind is in the gutter.  Feel free to make those changes and merge.

**Comment by karlp** [comment]
merged in cb0661f8 thanks!

**Pull request closed without merging**
