### PR TITLE
doc: clarify that usbd_register_control_callback() must be called from config callback

### PR DESCRIPTION
**Pull request by WGH-**

### CODE REVIEW

**Comment by WGH-** [comment]
This problem was seen before e.g. here https://github.com/libopencm3/libopencm3-examples/commit/393fe8e449d5334c715a3ca5f538328dbf387182

**Comment by karlp** [comment]
No, it's not must, it's _after_

The easiest way of doing that is inside the callback, but it doesn't have to be done there.

**Comment by WGH-** [comment]
Sound reasonable. Is changing "must" to "should" with clarification "or after" sounds good enough?

**Comment by karlp** [comment]
just change the "inside" to "inside or after" and we should be good to go.  I'll just do that now and merge it.

**Comment by karlp** [comment]
merged with some more rewording in f59d47c

**Pull request closed without merging**
