### PR TITLE
STM32F3: add HRTIM peripheral

### PR DESCRIPTION
**Pull request by florolf**
Add definitions for the High Resolution Timer peripheral (currently only present on the F334).

### CODE REVIEW

**Comment by karlp** [comment]
This  looks generally fine.  If you add a second * to all of your comments on the registter names and defintions, they'll automatically turn up all that wonderful text you entered into the doxygen.  (you can test it out yourself with ```make doc```)

**Comment by florolf** [comment]
Done, text now shows up in doxygen.

**Comment by florolf** [comment]
New version, fixes a logic error in the definitions of `HRTIM_FLTINR1_FLTxF_SHIFT`, `HRTIM_EECR_EExSRC_SHIFT` and `HRTIM_EECR3_EExF_SHIFT`.

**Comment by florolf** [comment]
Removed erroneous shifts from `HRTIM_CR1_ADxUSRC` enum values.

**Comment by OpenUAS** [comment]
@florolf, thx! very welcomed.

**Comment by karlp** [comment]
merged via rebase with extra docs in b2079f1..f475d45 thanks for this!

**Pull request closed without merging**
