### PR TITLE
Added SPI_SR_FRE constant (bit 8 of SPI_SR)

### PR DESCRIPTION
**Pull request by vampirefrog**

### CODE REVIEW

**Comment by karlp** [comment]
What target are you working with?  Can we find a better place for this?  F2/4 already has SPI_SR_TIFRFE for instance, for this bit.

**Comment by vampirefrog** [comment]
true, found it in stm32/f4/spi.h. in the reference manual it's simply called FRE, so I had trouble grepping for it. perhaps there should be an alias for it?

**Comment by karlp** [comment]
What target are you working on?

**Comment by vampirefrog** [comment]
F4

**Comment by karlp** [comment]
I think the SPI_SR_TIFRFE should just be replaced with SR_FRE, not this addition.  Don't have time to look further and just fix that myself right this moment though, writing this for next time.

**Comment by karlp** [comment]
this was resolved via bf125e9

**Pull request closed without merging**
