### PR TITLE
Renamed USB_DADDR_ENABLE to USB_DADDR_EF

### PR DESCRIPTION
**Pull request by kuldeepdhaka**
(USB_DADDR_EF is per datasheet)

### CODE REVIEW

**Comment by karlp** [comment]
valid, but minor, I'll merge this "later" when we get usb settled down, as I expect this will just make noise in the existing commits right now?

**Comment by kuldeepdhaka** [comment]
@karlp EF is as per datasheet. so take this as bug.

**Comment by karlp** [comment]
it's a "we didn't follow the exact recommendations of the hacking document" it's hardly a _bug_ but ok :)

**Comment by kuldeepdhaka** [comment]
past note: bufran wanted this
https://github.com/BuFran/libopencm3/commit/47cc93410be10dba4b57deb04a5ad96e0fbd1c63#diff-aac888ef9ba0bcfa5f3ddd94cb2ba061R79

**Comment by karlp** [comment]
merged via rebase in afefa68

**Pull request closed without merging**
