### PR TITLE
stm32: timer: Add missing TIMx_CCER bit definitions

### PR DESCRIPTION
**Pull request by 0xdec**
These are needed if you want to use channel 4 with a different polarity

### CODE REVIEW

**Comment by karlp** [comment]
What part are using?  Bit 15 exists in the f4, but I don't see bit 14 anywhere?  Just curious, extra bit definitions don't hurt anyone

**Comment by 0xdec** [comment]
You're right, I don't see bit 14 either, but I just assumed a different part might have it. I can remove it if you think that's better.

**Comment by 0xdec** [comment]
Removed bit 14 (TIM_CCER_CC4NE)

**Comment by karlp** [comment]
merged in 26ca4cc thanks

**Pull request closed without merging**
