### PR TITLE
Pulls/adc v2 f0 f3 review

### PR DESCRIPTION
**Pull request by karlp**
This is a stack of work on pulling out the common f0 and f3 (and l0 and l4)  

This is ready to merge by my account, with the test code in https://github.com/karlp/libopencm3-tests.

Fixes: https://github.com/libopencm3/libopencm3/pull/555 plus also
fixes channel sampling time ordering for f30x, which was already broken.

This is not a complete refactoring, work can continue, but it puts the framework in place, to just keep moving code as it is found to be common.

I plan on merging this "soon" unless there are strong objections to this.

### CODE REVIEW

**Comment by franzflasch** [comment]
Please can someone merge these changes into master asap? This fixes a lot bugs related to the f3!

Thanks!

**Comment by karlp** [comment]
@franzflasch just about there, had a bit of a break over easter, and am just running some final tests on this branch.

**Comment by franzflasch** [comment]
OK, great! We need this for a project here in Austria. I don't know what's exactly the problem, but without these changes I only get the ADC1 to work with the STM32F3. However we also need the ADCs 2,3 and 4. When I patch your changes into the library everything works fine.

**Comment by karlp** [comment]
this is merged now, or equivalents

**Pull request closed without merging**
