### PR TITLE
Regexp special characters need to be escaped inside regexp

### PR DESCRIPTION
**Pull request by Getty**
at least without this fix it was not working with my awk on debian stable

### CODE REVIEW

**Comment by karlp** [comment]
what are the symptoms of this failing?  how are you running this?

**Comment by karlp** [comment]
@Getty any follow up?  other people on debian have not been having problems, how exactly was it failing for you?

**Comment by Getty** [comment]
I must reconstruct what I was doing but this script is not part of the regular build process, so it is clear that not everybody reports it.

**Comment by karlp** [comment]
merged in 0cb1db0 thanks for filing this! we should have noticed earlier that it was just mawk/gawk!

**Pull request closed without merging**
