### PR TITLE
stm32: tests: make PA12 low

### PR DESCRIPTION
**Pull request by amitesh-singh**
D+ is PA12 not PA11.

### CODE REVIEW

**Comment by karlp** [comment]
Please use a branch for your PRs, rather than your own master branch.  Adding commits to  your own branch is automatically adding them to the PR.

**Comment by karlp** [comment]
(don't worry too much about it this time, I've just taken both of these now as they were easy, but please don't do this for PRs in teh future)

**Comment by amitesh-singh** [comment]
Thanks. I will do it from next time. github pull request is little weird though.

**Comment by karlp** [comment]
Just remember that a github PR is _tied_ to a single branch in your repository.  (So you want to use a branch that was pushed for the PR alone)

**Pull request closed without merging**
