### PR TITLE
STM32: add CAN support for stm32f3

### PR DESCRIPTION
**Pull request by nuft**
This enables the CAN support for stm32f3.
The code is almost the same, it just moved to the stm32/common/ folder.
The f3 has only one CAN interface, which resulted in some conflicts, so it had to be separated.
It is tested on f3 hardware.

### CODE REVIEW

**Comment by devanlai** [comment]
Were there any pending issues with this pull request that prevented it from being merged last year? I just tested out the CAN receive code on an STM32F042 after resolving the merge conflicts, and it worked fine for me.

Branch after resolving merge conflicts:
https://github.com/devanlai/libopencm3/tree/stm32f3_can

**Comment by nuft** [comment]
> Were there any pending issues with this pull request that prevented it from being merged last year?

Just some naming issues mentioned above, I think.

**Comment by karlp** [comment]
If all the original issues have been addressed, then please just make a new pull request from the branch you want.  There's no way I can look at this pull request, with 171 commits in it from some merging gone wrong.

**Comment by karlp** [comment]
Just to be clear, I'd still like to get the original changes merged, just not this particular branch with it's merge issues.

**Pull request closed without merging**
