### PR TITLE
stm32: l1: Add support for MCO setting.

### PR DESCRIPTION
**Pull request by iqyx**

### CODE REVIEW

**Comment by ChuckM** [comment]
looks good to me (code wise) but I don't have an L1 board to test it on.

**Comment by karlp** [comment]
This looks correct, I think I'll try and add this to the f3 as well, and pull it up to common code.

**Comment by esden** [comment]
@karlp do you want us to merge this for now and then refactor to be usable with F3 too? Or do you want to postpone this until we have the whole thing done?

**Comment by karlp** [comment]
@esden #425 has common MCO, but I've ignored the MCOPRE for now, it's not available on f1 and f3.

**Comment by karlp** [comment]
Closing this as #425 has merged, but if you want to work on MCO prescaler configuration, please file that as a new ticket.

**Pull request closed without merging**
